### ISSUE TITLE
Vampire Hunter instead of Night Warriors

### ISSUE THREAD

**Issue by sp1ashe** [poliva/fightcadestates#18]
Thanks for support always! I'm organizing Darkstalkers series tourney on Fightcade as a player "aku_reimu" and now wanna ask to exchange Night Warriors there for Vampire Hunter (ver950302JAPAN) for our future convenience. The reason is first that this game is known as Vampire Hunter worldwide and also has many fans in that Vampire/Darkstalkers category. As you see, there are currently many players in Vampire Savior room and some of them will try Vampire Hunter too. In my opinion there can be more new players expected if that game is categorized as Vampire series on Fightcade, or in other words now Night Warriors is isolated and not regarded. That must be disadvantage for Fightcade and players both. Then that version 950302JAPAN is actually best-selling one of all versions and still most popular since before. I'm glad if you understand these current situations around Vampire Hunter/Night Warriors, and post here my savestate for Vampire Hunter(ver950302JAPAN):

https://mega.co.nz/#!vAxi0SSJ!VKy_Jb6xhgqTnoveEEOFAltIpze6uoNsIGYN8NpQ8lc

This savestate is already tested in unsupported room and worked without desync during an hour play with friend there.

**Comment by poliva** [comment]
Hi @sp1ashe If i understand correctly, what you propose is to remove "nwarr" and add "vampj" instead, which is the japanese version of the same game, right?

@3xcl4m4t10n any comments?

**Comment by 3xcl4m4t10n** [comment]
I talked with several players and my conclusion was to let it be as it is now.

**Comment by sp1ashe** [comment]
@poliva yeah, they are essentially same games. The problem is rather how this game should be called and treated on Fightcade. I know the case about "Super Street Fighter II Turbo" and "Super Street Fighter II X", which are switched with introduction of Fightcade, and from that I had a question if that change is also possible about Night Warriors/Vampire Hunter. Maybe we have some different opinions like "nwarr" will stay for "vhuntjr2", or the both games will be playable, or remove one for another. As far i've played Night Warriors on Fightcade with other players, they say they want to play true Vampire Hunter (japanese version) on Fightcade and you'll see how often we have played/made contact with each other using Replay browser with search word "nwarr". Though Night Warriors is statistically not so popular as its sequel Vampire Savior, but on the other side people make always effort to pick up Vampire Hunter as the case in Japan shows: They did really big offline tournament with over 120 participants in last November and will have same scale of 3on3 tourney on this March. Well, cases are others from offline to online/Japan to other countries. But I thought we can also take part in making more fun and inspire all game communities using just another version of game. That is my opinion.
Anyway we will be glad, if that japanese version of Vampire Hunter is included on Fightcade! I leave Fightcade that decision to stay or change and I'll accept it.

**Comment by sp1ashe** [comment]
@3xcl4m4t10n I'm sorry that I didn't know that there were certain players who always played in that room before. Actually since I started to play there in last November, it seems there are usually just a few constant players that include me and some friends. (You'll see that with search word "nwarr" on Replay browser.) And I thought we can change the current situation better somehow, even if the topic "switching roms" is supposed to be experimental and risky at last. (In addition, latest released official "Dalkstalkers Resurrection(2013)" takes the above-mentioned Japanese version of Vampire Hunter for Night Warrior.)
Anyway I continue to play there and gather people by organizing tournaments constantly. It can lead to call the last players back, maybe. Thanks sincerely for your advises! That is all fro me :)

**Comment by sp1ashe** [comment]
I found a source about the differences of rom versions.
http://wiki.shoryuken.com/Night_Warriors:_Darkstalkers%27_Revenge#Version_Differences

As I refered, these minor changes are rather not important, because some play still the former version with bugs as Japanese do actually now, and others look the latter is fixed though they don't play this game eagerly in current. This is

**Comment by sp1ashe** [comment]
@3xcl4m4t10n I'm sorry that I didn't know that there were certain players who always played in that room before. Actually since I started to play there in last November, it seems there are usually just a few constant players that include me and some friends. (You'll see that with search word "nwarr" on Replay browser.) And I thought we can change the current situation better somehow, even if the topic "switching roms" is supposed to be experimental and risky at last. (In addition, latest released official "Dalkstalkers Resurrection(2013)" takes the above-mentioned Japanese version of Vampire Hunter for current Night Warriors' rom on Fightcade.)
Anyway I continue to play there and gather people by organizing tournaments constantly. I hope It will lead to call the last players back, maybe. Thanks sincerely for your advises! That is all from me :)

**Comment by sp1ashe** [comment]
Upps, I found a source about the differences of rom versions with help of a friend there.
http://wiki.shoryuken.com/Night_Warriors:_Darkstalkers%27_Revenge#Version_Differences

As I refered, these minor changes are rather not important, because some play still the former version with bugs as Japanese do actually now, and others look the latter is fixed though they don't play this game eagerly in current. This is the situation now.

**Comment by ciccioimberlicchio** [comment]
I'm the one who helped sp1ashe (Aku_reimu) finding that link, the reason we would like to have Vampire hunter instead of Night warriors aredifferent even if they may not sound that important:

Nwarr is a game that is not played that much in the first place but Vampire Savior/Darkstalkers enthusiast like me and many others sometimes hop in the room and play it, recently Aku_reimu started organizing tournament for both games

we would like to have Vhunt instead of Nwarr because it's basically the rom used in tournament plays in japan, it actually contains more dialogues wich are cutted out from the European rom, the glitches are still the same except that Phobos/Huitzil j.mp knocks down the opponent but that's not a big deal (and for being nitpicky SF2x had that zangief "1 hit = stun" thing too in the japanese rom but people seems to not care about so wy whould they for this game?).

i dont' understand this "many players prefer stick with Nwarr", what players? those one in SF room that barely touched the game and never plays it? to be 100% honest i wouldn't mind to stick with Nwarr at first but now that finally more people started playing it i don't see why switching to the Japanese version, just for make happy those few fan of the game like me and the one who every week joins the tournament, i have no idea what work you have to do for switch a rom and i don't know if it's hard or not, but it would be appreciated for us who love Fighcade and the Darkstalkers :3

Also i tested the rom with Aku_reimu and Utopi and it played fine, the only thing was that you never started from the character Select screen when i played it in the Unsupported games room

I would create a savestate by myself if you guys tell me how to do (i would also make a snow bros one but that's an other story lol)
And i guess it would be fun to have the First Darkstalkers/Vampire game on Fightcade too, but that's an other story

In the end, these are my motivations, i guess some people will agree with me and other maybe not, who knows.

**Comment by sp1ashe** [comment]
@ciccioimberlicchio the savestate above starts from character select and also freeplay setting same as other fightings on Fightcade. i updated the last one which we tested once together.

**Comment by ciccioimberlicchio** [comment]
that's perfect!

**Comment by poliva** [comment]
changes are live

**Comment by poliva** [comment]
Apparently i made a wrong change, thanks @ciccioimberlicchio from notifiying it.
I have reverted back the change and left things as they were before.

Please let me know which is the japanese version that should be added in the place of <b>nwarr</b> and provide a proper savestate:
'<b>vhuntj</b>': "Vampire Hunter - darkstalkers' revenge (950316 Japan)"
'<b>vhuntjr1</b>': "Vampire Hunter - darkstalkers' revenge (950307 Japan)"
'<b>vhuntjr2</b>': "Vampire Hunter - darkstalkers' revenge (950302 Japan)"

**Comment by sp1ashe** [comment]
@poliva @ciccioimberlicchio  'vhuntjr2': "Vampire Hunter - darkstalkers' revenge (950302 Japan)" is the right version. Savestate link https://mega.co.nz/#!vAxi0SSJ!VKy_Jb6xhgqTnoveEEOFAltIpze6uoNsIGYN8NpQ8lc

**Comment by ciccioimberlicchio** [comment]
we tested the rom vhuntjr2 and it played perfectly, Reimu made the savestate of it.
 standing to Aku_reimu this is the rom of the board who's played in tournaments.i think we can use that one

I tested the rom again today just for 10 minutes but the game didn't seemed to desync, i'll test again later and i'll let you guys know

also was nice to have the first game too but it was already removed ahah

**Comment by poliva** [comment]
Thanks for the comments, changes will be live in the next server restart.

Regarding the other game "Vampire", i guess it's the same as "Darkstalkers". If you want it included, please test if any of the available versions works fine for online playing (no synchronization issues after some time playing) and I will add it. To my understanding it should be one of the following games:

'<b>dstlk</b>': 'Darkstalkers - the night warriors (940705 Euro)'
'<b>dstlka</b>': 'Darkstalkers - the night warriors (940705 Asia)'
'<b>dstlku</b>': 'Darkstalkers - the night warriors (940818 USA)'
'<b>dstlkur1</b>': 'Darkstalkers - the night warriors (940705 USA)'
'<b>vampj</b>': 'Vampire - the night warriors (940705 Japan)'
'<b>vampja</b>': 'Vampire - the night warriors (940705 Japan, alt)'
'<b>vampjr1</b>': 'Vampire - the night warriors (940630 Japan)'

**Comment by ciccioimberlicchio** [comment]
Today i saw that on fightcade there was the Vampj rom, for what i know this game was really never played in tournaments so any versions may be ok,i think that is better add Vampj so we'll have all the game listed in order (Vampire, Vampire hunter, Vampire Savior) and it would be less annoying for everyone to switch in between rooms  i'll test again the Vampj rom today in unsupported and i'll let you know if we have desyncs or there's some problems

**Comment by 3xcl4m4t10n** [comment]
I have an idea: Why just add here a game list with the rom name of the right one to use on Fightcade? I see senseless to have the same game on two different versions. It is something like the case of Breakers/Breaker's Revenge or Jojo's Venture/Jojo's Bizarre Adventure, those rooms are always completly empty.

So please, just add the correct list and avoid to repeat the same game only with regional difference. I think it  is the best we can do for Fightcade and p0f.

**Comment by ciccioimberlicchio** [comment]
well there's nothign that will get "repeated" we're just asking to CHANGE the game, if Vampire Hunter will get added Night warriors will not be avaiable on Fightcade anymore

also: the first Vampire is not even in the fightcade game list so, i don't get your point to be honest :(

**Comment by 3xcl4m4t10n** [comment]
MAh, i just missunderstood something between this massive issue XD. Sorry, sorry... I exit now...

http://stream1.gifsoup.com/view4/4705437/quick-exit-glass-door-o.gif

**Comment by Rotanibor** [comment]
Oh, I've been lazy about handling the Vampire Hunter problem but intended to get to it eventually. I can confirm that 950302 is the correct release, so we should be good there. Not sure off hand if there are any incorrect settings in the menu but I don't think there is much to get wrong there besides having it on Turbo 1, Freeplay and Auto turned off. If the room name changes to "Vampire Hunter" to reflect the change that would be great.

As far as the first game, Vampire: The Night Warriors, I've been meaning to get it added as well and this is a good time. There is indeed differences between region and version number. I'm more familiar with the region differences rather than the version differences, the region standard being the Japanese version. I don't think there are big differences between the Japanese versions, I can test a few bugs to see if they work in the later one, but I'd tentatively suggest going with the first Japanese release at the moment. I'll test it out after finishing this post.

A potentially bigger problem with Vampire is there doesn't seem to be a standard Turbo setting for tournaments. Turbo 3 is avoided since it makes dashing incredibly difficult. I've seen Japanese tournaments for the game ran in both Turbo 1 and Turbo 2, and a western scene never existed so there is no standard to draw from there. I prefer Turbo 2 myself and its how we played it whenever we touched the game on GGPO at least, though we could have it set to Free Select. If we do Free Select I'd suggest putting a warning on the top of the screen when you join the room to avoid Turbo 3, lol.

**Comment by Rotanibor** [comment]
I forgot to reply to this earlier, but when we played on GGPO before we used 'vampjr1': 'Vampire - the night warriors (940630 Japan)' quite extensively, with no desyncs. I don't imagine that would change with FightCade.

I looked over it just now and the primary stuff that was taken out of the release for Vampire in the US version is in all the Japanese versions, I'll say lets just go with the earlier one to be safe and because we've already tested it extensively.

*COIN — 1 COIN 1 CREDIT -or- 1 COIN 8 CREDIT (Fills up to 9 coins max, and if you have it set to 1 COIN 8 CREDIT you can't add any credits until the total in the game will equal a number that is 9 or less, kind of weird.)
*GAME DIFFICULTY	 — "I'd personally say '1 EASIEST', just so you can practice safely between matches."
*DAMAGE LEVEL — 5 MEDIUM
*TIME COUNT SPEED — NORMAL COUNT DOWN
*SOUND — STEREO
*DEMO SOUND — ON (Defaults to 'OFF' so change this.)
*CONTINUE — ON
*START MODE — ? (The default is ON... not sure what this does tbh.)
*MONITOR FLIP — OFF
*MAX ROUND — 3 ROUNDS
*REGULATION — OFF
*GAME SPEED — FREE SELECT -or- TURBO 2

I'm going to ask around and see what people want for the TURBO speed.

**Comment by ciccioimberlicchio** [comment]
We just finished testing the game 

'vampj': 'Vampire - the night warriors (940705 Japan)'

We played for like an hour and we haven't got any problem at all

our setting were the same except that we were using turbo 3 buti fixed the savestate, here it is

https://www.mediafire.com/?b224my332zet6b6

**Comment by Rotanibor** [comment]
I recommend going with vampjr1 to be safe, as it was released first. As far as old 90's arcade games go, the original release is typically always the standard, especially with CPS2/3 games.

**Comment by ciccioimberlicchio** [comment]
i tought the original was Vamprj, i'll make a savestate of that one soon then
