### ISSUE TITLE
Question: How to contribute to Fightcade

### ISSUE THREAD

**Issue by Toothpick2600** [poliva/fightcadestates#46]
Apologies if this is not the proper section to ask this sort of thing, but I recently got into Fightcade, and I want to help contribute to improve the game library. The main website says that Fightcade is capable of running a game supported by the version of FBA that comes with it. So my question(s): What is FBA? How do I know if a game is FBA compatible or not? How do I gain access to any necessary savestates used to test the game? Where do I find said savestate, and if I get one, where do I send them?
Thanks.

**Comment by 3xcl4m4t10n** [comment]
Hello Toothpick2600,

With the permision of pof i am going to answer you:

-If you used Fightcade then you are using FBA. If you read on the windows with the game it say "FB Alpha" ;D. Final Burn Alpha is an emulator created by Barry. You can check him website here:

http://www.fbalpha.com/

You just need to check it compatibility list and check if the game you are interested on is available or not. Keep on mind that Fightcade use an old version of FBA but you can check it list by opening the FBA executable.

-You are not going to gain access because there's no savestates repository: All the games that are supported by now are on Fightcade. In theory, all the games on FBAlpha are compatible with Fightcade but there's some exceptions like Snow Bros. Pof is adding games if them are compatibles and if there's a minimum amount of people interested on the particular game.

By the way you have the unsupported room where you can play any game with anybody. Just read the easy steps you have on the room when you enter there.

**Comment by Toothpick2600** [comment]
Okay, much appreciated, thank you for going into more detail.
