### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by abradley2** [poliva/fightcadestates#70]
There doesn't seem to be any documentation on the creation of proper save state files.

On the fightcade website it states:

> If it is supported and you want it included in the next update, please send us a good savestate file for the game using a pull request or opening an issue to the savestates repository. Make sure the game works fine by playing it in the "Unsupported Games" room first.

It may be helpful if a link is included here to documentation regarding the schema of these files.

**Comment by 3xcl4m4t10n** [comment]
You don't need a lot of information :D. Only:

· Is the game supported by the actual version of FBA?
· Does it have an interesting simultaneous 2P mode?
· It's working on FightCade? Please, note that this is different from the first question. Working on FBA doesn't mean it is going to work with GGPO/FightCade netcode. For example, Snow Bros. doesn't work with the netcode, that's why you need to try it first.

After that, I can make the save state without problem.

**Comment by abradley2** [comment]
I would actually prefer to make the save state file myself if possible, which is why I'm curious as to whether there is documentation for this.

**Comment by 3xcl4m4t10n** [comment]
No, there's no official documentation. Just made the savestate with the steps I told you and send it to me (you can attach files here) and I'll check it out. What made are you interesting on?

**Comment by SetoNaikai** [comment]
Interested in yoshi's cookie for nes 2p (the SNES version of the game is a little too slow) ran across the game recently and it is one of the best two player games I have ever played. Perfect for beginners and experts. Real gem.
